### ISSUE TITLE
Running Clinker on single-end RNA-seq data

### ISSUE THREAD

**Issue by yunkaig** [Oshlack/Clinker#12]
Hello and Happy New Year,

I'm completely new to Clinker and just started to run it on some quite old RNA-seq data. And an error occurred at **plot_fusion** stage (or see the output file from bpipe):

    Unable to locate one or more specified inputs from pipeline with the following extension(s): (.*)_R2.fastq.gz"

Seems it is asking for a paired-end data set. However I checked the source code in clinker.pipe and found the line:

    "transform("(.*)_R1.fastq.gz","(.*)_R2.fastq.gz") "

in multiple stages: star_align, index_bams, prepare_plot, plot_fusion. So I am confused at how the pipe manage to run through the 3 tests and stuck on the 4th.

Is there a way to fix this?

[clinker_out_134159-11-00_S5_L001_R1_001.fastq.txt](https://github.com/Oshlack/Clinker/files/2719962/clinker_out_134159-11-00_S5_L001_R1_001.fastq.txt)

**Comment by breons** [comment]
Hi @yunkaig, thanks for trying Clinker! 

If you setup the following visualisation with your current results, what do you see?
https://github.com/Oshlack/Clinker/wiki/4.-Running-the-pipeline#viewing-results

If that all looks good, I'll have a play and will get it working for you :).

Cheers,
Breon.

**Comment by yunkaig** [comment]
Hi thank you for your timely reply.

Here are some screenshots from IGV and the tracks, Sashimi plots all look good.

<img width="962" alt="screen shot 2019-01-03 at 9 57 45 am" src="https://user-images.githubusercontent.com/46309749/50616841-50d47280-0f3e-11e9-8370-d0de56298486.png">
<img width="962" alt="screen shot 2019-01-03 at 9 57 15 am" src="https://user-images.githubusercontent.com/46309749/50616842-516d0900-0f3e-11e9-9e83-13fea8fef630.png">
<img width="1150" alt="screen shot 2019-01-03 at 9 55 34 am" src="https://user-images.githubusercontent.com/46309749/50616843-516d0900-0f3e-11e9-9dc1-0ef8ebbc0a8f.png">
<img width="963" alt="screen shot 2019-01-03 at 9 56 57 am" src="https://user-images.githubusercontent.com/46309749/50616844-516d0900-0f3e-11e9-93d2-ec87f50d2d60.png">

**Comment by breons** [comment]
Hi again! 

Could you try changing the following in **workflow/clinker.pipe - line 482**:

`transform("(.*)_R1.fastq.gz","(.*)_R2.fastq.gz") to ("${fusion_friendly}.pdf") {`
to 
`transform("(.*)_R1.fastq.gz","(.*)_R2.fastq.gz") {`

This shouldn't result in any significant changes to the program, but it might solve your problem. If it works for you, please let me know and I will make the change in the next release.

Cheers,
Breon.

**Comment by yunkaig** [comment]
Hi!

I have rerun clinker with the change you said and it worked! 
Thank you very much Breon!

Cheers,
Yunkai

**Comment by breons** [comment]
Fantastic!

If you want any adjustments or come across any other issues, just let me know :).
