### ISSUE TITLE
Assign to global variable files

### ISSUE THREAD

**Issue by cytcc123** [Oshlack/Clinker#16]
Hi,

When I run the test files, the command is like this: 
bpipe -p out=/proj/snic2019-8-2/miniconda3/clinker/output/run -p caller=$CLINKERDIR/test/caller/bcr_abl1.csv -p col=1,2,3,4 -p genome=19 -p print=true -p competitive=true -p header=true -p align_mem=32000000000 -p genome_mem=32000000000 -p fusions=BCR:ABL1 $CLINKERDIR/workflow/clinker.pipe /proj/snic2019-8-2/miniconda3/clinker/Clinker/test/fastq/test_R1.fastq.gz /proj/snic2019-8-2/miniconda3/clinker/Clinker/test/fastq/test_R2.fastq.gz

But I encountered errors.

===================================== Stage star_align (test) ======================================
ERROR: stage star_align failed:

     An attempt was made to assign to global variable files after your pipeline already
     started running. To ensure thread safety, global variables may only be assigned
     before the pipeline starts. Solutions include:

      - add 'def', 'var', or 'requires' before this assignment to define a local variable,
        eg: def files = "/proj/snic2019-8-2/miniconda3/clinker/Clinker/test/fastq/test_R1.fastq.gz /proj/snic2019-8-2/miniconda3/clinker/Clinker/test/fastq/test_R2.fastq.gz" or: var files : "/proj/snic2019-8-2/miniconda3/clinker/Clinker/test/fastq/test_R1.fastq.gz /proj/snic2019-8-2/miniconda3/clinker/Clinker/test/fastq/test_R2.fastq.gz"
      - define a branch variable using: branch.files = "/proj/snic2019-8-2/miniconda3/clinker/Clinker/test/fastq/test_R1.fastq.gz /proj/snic2019-8-2/miniconda3/clinker/Clinker/test/fastq/test_R2.fastq.gz"

     You can disable this behavior at your own risk by setting allowGlobalWrites=true in
     your bpipe.config file.

========================================= Pipeline Failed ==========================================

One or more parallel stages aborted. The following messages were reported:

-------------------------------------- star_align  ( test )  ---------------------------------------

     An attempt was made to assign to global variable files after your pipeline already
     started running. To ensure thread safety, global variables may only be assigned
     before the pipeline starts. Solutions include:

      - add 'def', 'var', or 'requires' before this assignment to define a local variable,
        eg: def files = "/proj/snic2019-8-2/miniconda3/clinker/Clinker/test/fastq/test_R1.fastq.gz /proj/snic2019-8-2/miniconda3/clinker/Clinker/test/fastq/test_R2.fastq.gz" or: var files : "/proj/snic2019-8-2/miniconda3/clinker/Clinker/test/fastq/test_R1.fastq.gz /proj/snic2019-8-2/miniconda3/clinker/Clinker/test/fastq/test_R2.fastq.gz"
      - define a branch variable using: branch.files = "/proj/snic2019-8-2/miniconda3/clinker/Clinker/test/fastq/test_R1.fastq.gz /proj/snic2019-8-2/miniconda3/clinker/Clinker/test/fastq/test_R2.fastq.gz"

     You can disable this behavior at your own risk by setting allowGlobalWrites=true in
     your bpipe.config file.

----------------------------------------------------------------------------------------------------

Use 'bpipe errors' to see output from failed commands.

Could you tell me how to fix that problem?

Thanks a lot,
Yi

**Comment by breons** [comment]
Hi Yi,

I think I have encountered this using recent versions of bpipe. Could you please try version 0.9.9.5?
https://github.com/ssadedin/bpipe/releases/tag/0.9.9.5

Let me know how you go.

Thanks for trying Clinker!
Breon.

**Comment by cytcc123** [comment]
Hi Breon,

I tried version 0.9.9.4, 0.9.9.5 and 0.9.9.7, the problems always exist.

Best,
Yi

**Comment by breons** [comment]
Hi Yi,

I cloned the current version and encountered the same error when running bpipe 0.9.9.7. However, switching to 0.9.9.5 allowed my pipeline to progress.

Hopefully it's just a case of your bpipe version not switching. If not, I'll look into resolving the issue in 0.9.9.7 which will hopefully solve your problem also!

Cheers,
Breon.

**Comment by cytcc123** [comment]
Hi Breon,

I encountered the same problems when running both 0.9.9.5 and 0.9.9.7. 
Could you help me solve that problems?

Thank you so much,
Yi

**Comment by breons** [comment]
Hi Yi,

I've updated the repository with a potential solution for you (also some other things). Hopefully you can try that and have some success!

Please let me know if you're still not successful, if not please close the issue.

Thanks!
Breon.
