### ISSUE TITLE
Error from test example

### ISSUE THREAD

**Issue by c4cactus** [Oshlack/Clinker#18]
Hi Alicia,

Versions -
- Clinker: latest version 
- R: 3.6.1
- Bioconductor: 3.10
- STAR: 2.7.3a

I got the following error when running test example:

===================================== Command plot_fusion (34) =====================================

Command    : Rscript /opt/tools/Clinker/plotit/fst_plot.r /opt/tools/Clinker/test/test_out BCR:ABL1 /opt/tools/Clinker/test/test_out/alignment/test/BCR_ABL1 16 9 1,3,1,2,4,2 /opt/tools/Clinker/test/test_out/alignment/test test 6e65ad,3983AA,2b749a,f05f3b,a1d16e,f2ffe4,215A4A,D7D4E4,6e65ad,ff6d6d axis,coverage,gene,domain,transcript,sashimi 2
Started    : Wed Jun 10 17:38:32 SGT 2020
Stopped    : Wed Jun 10 17:39:09 SGT 2020
Exit Code  : 1
Config:
                   Name           |  Value
          ---------------------------------
          max_per_command_threads | 16
          executor                | local
          stats_update_interval   | 120000
          outputScanConcurrency   | 5
          maxFileNameLength       | 2048
          name                    | Rscript
          procs                   | 1

Output    :

        [1] "Plotting: BCR:ABL1"
        [1] "------------------------------------------------------"
        [1] "Libraries and ancillary files loaded. Creating Tracks."
        Error in validObject(.Object) :
          invalid class "ReferenceAlignmentsTrack" object: The referenced file '/opt/tools/Clinker/test/test_out/alignment/test/BCR_ABL1/splice_junction_reads.bam' does not exist
        Calls: prepare ... initialize -> .local -> <Anonymous> -> .local -> validObject
        In addition: Warning message:
        In if (annotations$proteins != FALSE) { :
          the condition has length > 1 and only the first element will be used
        Execution halted

**Comment by breons** [comment]
Howdy, thanks for trying Clinker! 

First of all, what .bam files have been created in `/opt/tools/Clinker/test/test_out/alignment/test/BCR_ABL1/`? 

That file should have been generated in the previous stage "prepare_plot".

**Comment by c4cactus** [comment]
Thanks for following up!

I found the culprit, I didn't install samtools in conda, as an early version is available and in path, butttt the version is different, and not able to generate splice_junction_reads.bam.

Followed instruction to install samtools in conda, and now test bpipe can run till "Pipeline Succeeded"! WOOT!

**Comment by breons** [comment]
Good work finding the issue! Please let me know if you have any further questions.
