### ISSUE TITLE
Reads don't align on the fusion junction

### ISSUE THREAD

**Issue by dplassard** [Oshlack/Clinker#27]
Hello,

Thank you for building such a tool, it is exactly what I need. However, I have the following error no matter which fastq I use. For example, if I use your test data and if I execute the following command as available in your wiki :

bpipe -p out="/shared/ngs/illumina/common/project/2022/S22072/221220_Test_clinker" -p caller=$CLINKERDIR/test/caller/bcr_abl1.csv -p col=1,2,3,4 -p genome=19 -p print=true -p competitive=true -p header=true -p threads=10 -p align_mem=80000000000 -p genome_mem=80000000000 -p fusions={BCR:ABL1} $CLINKERDIR/workflow/clinker.pipe $CLINKERDIR/test/fastq/*.fastq.gz

I have this error:

===================================== Stage plot_fusion (test) =====================================
[1] "Plotting: {BCR:ABL1}"
[1] "------------------------------------------------------"
[1] "Libraries and ancillary files loaded. Creating Tracks."
[1] "There are no fusion junctions with a read support greater than 1"
[1] "Terminating plotting for this fusion."
NULL
ERROR: Expected output file /shared/ngs/illumina/common/project/2022/S22072/221220_Test_clinker/plots/test/{BCR_ABL1}.pdf in stage plot_fusion (test) could not be found 

I suppose there are reads on the fusion in your test data? With my data, I have the same problem. Do you know what the problem is?

Thank you in advance,
Best regards
Damien Plassard

**Comment by breons** [comment]
Hi Damien,

Could you please do a `grep BCR:ABL1 /shared/ngs/illumina/common/project/2022/S22072/221220_Test_clinker/reference/fst_reference.fasta` and verify that the test fusion exists there? Does your fusion exist in there, i.e. `grep GENE1:GENE2 fst_reference.fasta`?

**1. If BCR:ABL1 does not exist but your fusion does**
Head over to `/shared/ngs/illumina/common/project/2022/S22072/221220_Test_clinker/alignment/*name*/*FUSION*/junctions.txt` and check whether your desired fusion is in there (with the correct breakpoints).

If it does, there's a problem with the plotting step, if it doesn't and you're sure this fusion exists, then we can look into that further.

**2. If no to both:** 

Could you try running the below to get a fresh run with just the test:
`mkdir /shared/ngs/illumina/common/project/2022/S22072/221220_Test_clinker_2`
```
bpipe -p out="/shared/ngs/illumina/common/project/2022/S22072/221220_Test_clinker_2" -p caller=$CLINKERDIR/test/caller/bcr_abl1.csv -p col=1,2,3,4 -p genome=19 -p print=true -p competitive=false -p header=true -p threads=10 -p align_mem=80000000000 -p genome_mem=80000000000 -p fusions="BCR:ABL1" $CLINKERDIR/workflow/clinker.pipe $CLINKERDIR/test/fastq/*.fastq.gz
```
Note that I have set `competitive=false` above to speed this example up for you (adjust resources if you like).

If that works, it's installed correctly.

Let me know how you go,
Breon.

**Comment by dplassard** [comment]
Hi Breon,

Thank you for your response! I did a grep and it worked:
grep BCR:ABL1 /shared/ngs/illumina/common/project/2022/S22072/221220_Test_clinker/reference/fst_reference.fasta
>BCR:ABL1

So I launched your command and it worked too, the graphs are generated. However, if I launch the same command but setting competitive=true, it doesn't work anymore:

==================================== Stage prepare_plot (test) =====================================

BCR:ABL1
------------------------------------------
filtering BAM file for fusion of interest
filtering BAM file for reads with overhangs < 2 (noise reduction)
Creating ancillilary files
Index BAM files
[E::hts_parse_region] Range is ambiguous. Use {BCR:ABL1} or {BCR}:ABL1 instead
[main_samview] region "BCR:ABL1" specifies an invalid region or unknown reference. Continue anyway.

===================================== Stage plot_fusion (test) =====================================
[1] "Plotting: BCR:ABL1"
[1] "------------------------------------------------------"
[1] "Libraries and ancillary files loaded. Creating Tracks."
[1] "There are no fusion junctions found in this gene pair."
[1] "Terminating plotting for this fusion."
NULL
Error in read.table(locations$junctions) : no lines available in input
ERROR: Expected output file /shared/ngs/illumina/common/project/2022/S22072/221220_Test_clinker_2/plots/test/BCR_ABL1.pdf in stage plot_fusion (test) could not be found 

In this case, the alignment/*name*/*FUSION*/junctions.txt file is empty.  If I use {BCR:ABL1} as suggested in the message, I have the same error as in my first post (but junctions.txt file is no longer empty). I don't really understand...

Best regards,
Damien

**Comment by breons** [comment]
As it's currently been implemented you need to "start from scratch" with every time you change the snippet which would change the output of `fst_reference.fasta`. 

When you changed `competitive=true` was this I'm the results folder with the already generated plots? If so, try removing the contents of that folder or creating a new one and see if that works.

**Comment by dplassard** [comment]
Between each execution of the tool I removed the output folders and yes, the first time I have changed to {BCR:ABL1}. In both cases (BCR:ABL1 or {BCR:ABL1}), I have an error message but they are not the same.

**Comment by breons** [comment]
If you have `competitive=false` on your fusion and data, do you get a plot?

Can you post the output of `grep BCR:ABL1 junctions.txt` on the failing junctions.txt file (where `competitive=true` and using the test data)? 

What version of STAR are you using?

**Comment by dplassard** [comment]
Yes when I have competitive=false, I get a plot.

If I set competitive=true (and writing BCR:ABL1, not {BCR:ABL1}), the junctions.txt file is empty:
grep BCR alignment/test/BCR_ABL1/junctions.txt 

fusion_breakpoint_reads.bam and splice_junction_reads.bam are also empty. And I have no error in the STAR log files (files in attached).

In these tests, I am using version 2.5.3a (I also tested other versions but, either I have the same problem, or I get a segmentation fault).

[Log.final.out.txt](https://github.com/Oshlack/Clinker/files/10417064/Log.final.out.txt)
[Log.out.txt](https://github.com/Oshlack/Clinker/files/10417065/Log.out.txt)

**Comment by breons** [comment]
Ok, could I get the junctions.txt output when you set {BCR:ABL1}? 

At the moment I'm trying to determine whether the plotting step is failing in the presence of correctly mapped reads across the junction or whether something Iis happening upstream with the super transcript alignment.

If you view the competitively aligned result in igv 
(https://github.com/Oshlack/Clinker/wiki/4.-Running-the-pipeline#igv) can you view the reads crossing the breakpoint?

**Comment by dplassard** [comment]
You can find the junction.txt file attached. If I view the result in IGV, we can see no read crossing the breakpoint, the coverage is 0 at this location (I did a screenshot, you can also see it in attachment).

[junctions.txt](https://github.com/Oshlack/Clinker/files/10418321/junctions.txt)
<img width="1418" alt="IGV_{BCR_ABL1}" src="https://user-images.githubusercontent.com/54101764/212486353-708c606c-963f-4790-a57b-e8ac84a61665.png">

**Comment by breons** [comment]
So that junctions.txt is correct - likely everything has worked until this stage.

I've run the test using `fusions={BCR:ABL1}` and I get the same problem. If I run it with `fusions=BCR:ABL1` it runs as expected with `competitive=true` and I don't get the same error.

What version of samtools are you running? I'm running `v1.4.1` which doesn't seem to bring up the below error you experience: 
`[E::hts_parse_region] Range is ambiguous. Use {BCR:ABL1} or {BCR}:ABL1 instead` 

Could you try running the below for me (set `results=your output (/shared/ngs/illumina/common/project/2022/S22072/221220_Test_clinker)`? 

```Rscript $CLINKERDIR/plotit/fst_plot.r $results BCR:ABL1 $results/alignment/test/BCR_ABL1 16 9 1,3,1,2,4,2 $results/alignment/test test 6e65ad,3983AA,2b749a,f05f3b,a1d16e,f2ffe4,215A4A,D7D4E4,6e65ad,ff6d6d axis,coverage,gene,domain,transcript,sashimi 2```

**Comment by breons** [comment]
Hi Damien,

It turns out `samtools > 1.11` will complain about `{BCR:ABL1}`. Given samtools is at `v1.16` now, I think I should be supporting this.

I've pushed a change recently that will (hopefully) get you running with the below if you pull the latest from the repo:
`bpipe -p out="/shared/ngs/illumina/common/project/2022/S22072/221220_Test_clinker" -p caller=$CLINKERDIR/test/caller/bcr_abl1.csv -p col=1,2,3,4 -p genome=19 -p print=true -p competitive=true -p header=true -p threads=10 -p align_mem=80000000000 -p genome_mem=80000000000 -p fusions=BCR:ABL1 $CLINKERDIR/workflow/clinker.pipe $CLINKERDIR/test/fastq/*.fastq.gz`

Otherwise you can now just visit `cd $CLINKERDIR/test` and do `./test-installation.sh` and then visit `cd $CLINKERDIR/test/results` to get the results.

The test should also look different, with this example being more typical of a fusion gene with a clear drop in coverage between the breakpoints.

If that all works, hopefully your samples and fusion gene of interest will run through. Let me know if not.

Hope that helps,
Breon.

**Comment by dplassard** [comment]
Hi Breon,

I am running v1.12 of samtools. I pull the latest from the repo and the test works well. I also run the tool with my samples, and there are not error anymore, everything works fine now.

Thank you for solving the problem and for your time,
Best regards,
Damien

**Comment by breons** [comment]
You are very welcome. All the best.
