### ISSUE TITLE
Matrix dimension error during plotting stage

### ISSUE THREAD

**Issue by pwaltman** [Oshlack/Clinker#4]
This is an error that I keep getting (more comments below)

```
=================================== Stage plot_fusion (CUAC1855) ===================================
[1] "Plotting: SLC16A7:ZNF621"
[1] "------------------------------------------------------"
[1] "Libraries and ancillary files loaded. Creating Tracks."
Error in matrix(unlist(value, recursive = FALSE, use.names = FALSE), nrow = nr,  :
  length of 'dimnames' [2] not equal to array extent
Calls: prepare -> [ -> [.data.frame -> Ops.data.frame -> matrix
Execution halted
ERROR: Command failed with exit status = 1 :
```

After some debugging on my part, it seems like the matrix that's stored in the junctions.txt file that is generated ends up having 0 rows in it just prior to this error getting thrown. I tried debugging the code that generates the junctions.txt, but it is an indecipherably piece of awk code, and I gave up.

FWIW, this is the contents of the junctions.txt file:
```
SLC16A7:ZNF621  12566   12801   0       5
SLC16A7:ZNF621  12887   13016   0       1
SLC16A7:ZNF621  12888   13014   0       4
SLC16A7:ZNF621  13658   18138   0       1
SLC16A7:ZNF621  381     646     0       3

```

**Comment by breons** [comment]
Hi there, thanks for trying Clinker! Sorry you ran into some troubles, I'm here to help.

Can you please give me the SLC16A7:ZNF621 entries in the annotations/gene_boundaries.bed file? I just need to know where one superTranscript ends and the other begins.

**Comment by breons** [comment]
Howdy. Not sure if you still need assistance, but I've made some updates to Clinker which might help you. 

Can you try pulling the latest version and trying again? If you run into trouble, try setting **support=1** in the bpipe command.

**Comment by breons** [comment]
Closing due to some reworking of that part of the software and no responses to my replies, but please reopen if more assistance is needed! Happy to help.
