### ISSUE TITLE
plot_fusion stage fails on test data

### ISSUE THREAD

**Issue by MrsLaviniaG** [Oshlack/Clinker#5]
Hello, love the efforts that you have made on the documentation!, very thorough.
I am running into an issue with the first example (BCR:ABL1)

===================================== Stage plot_fusion (test) =====================================
[1] "Plotting: BCR:ABL1"
[1] "------------------------------------------------------"
[1] "Libraries and ancillary files loaded. Creating Tracks."
Error in file(file, "rt") : cannot open the connection
Calls: prepare -> as.data.frame -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/g/data/gx8/extras/gordonl/clinker_results/annotation/transcripts.gtf': No such file or directory
Execution halted
ERROR: stage plot_fusion failed: Command in stage plot_fusion failed with exit status = 1 :

The annotation folder exists but just with an exon_boundaries.bed file and a gene_boundaries.bed file.  Any help appreciated, thanks!

**Comment by breons** [comment]
Thanks! I really hope it's easy for people, please let me know if you have any suggestions to make it more intuitive.

That is an unusual hiccup, may I get the snippet that you are running the pipeline with? Also, what operating system are you working with?

The very first stage of the pipeline creates that file, so the very first step would be deleting /reference/fst_reference.fasta (only this one file!) and rerunning the pipeline using the same snippet. If the file still hasn't been generated after that step and you receive another error at the plotting, then we can debug it further :).

**Comment by MrsLaviniaG** [comment]
wow, that was fast!
Running on a cluster (Linux x86_64)
Following your first example with:

bpipe -p out=/g/data/gx8/extras/gordonl/Clinker/clinker_results -pcaller=$CLINKERDIR/test/caller/bcr_abl1.csv -p coo
l=1,2,3,4 -p genome=19 -p print=true -p competitive=true -p header=true -p align_mem=4000000000 -p genome_mem=310255992405 -p fusions=BCR:ABL1 $CLINKERDIR/workflow/clinker.pipe $CLINKERDIR/test/fastq/*.fastq.gz

I'll follow your suggestions and get back to you.

**Comment by MrsLaviniaG** [comment]
Ok first rerun gives me:

Warning message:
In read.dcf(con) :
  URL 'http://bioconductor.org/BiocInstaller.dcf': status was 'Couldn't resolve host name'
Request to BioMart web service failed.
The BioMart web service you're accessing may be down.
Check the following URL and see if this website is available:
http://www.ensembl.org:80/biomart/martservice?type=registry&requestid=biomaRt
Error in if (!grepl(x = registry, pattern = "^\n*<MartRegistry>")) { :
  argument is of length zero
Calls: prepare -> create -> prepAnnotation -> useMart -> listMarts
Execution halted
ERROR: stage plot_fusion failed: Command in stage plot_fusion failed with exit status = 1 :

I would say this is because it is a worker node without access to the internet, I'll try on the login node.

**Comment by breons** [comment]
Thanks, just note that there are some missing spaces in the snippet above (probably a typo entering it in a reply)

bpipe -p out=/g/data/gx8/extras/gordonl/Clinker/clinker_results **-p c**aller=$CLINKERDIR/test/caller/bcr_abl1.csv -p **col**=1,2,3,4 -p genome=19 -p print=true -p competitive=true -p header=true -p align_mem=4000000000 -p genome_mem=310255992405 -p fusions=BCR:ABL1 $CLINKERDIR/workflow/clinker.pipe $CLINKERDIR/test/fastq/*.fastq.gz

Try setting competitive=false for this one, the image won't look too good, but it will verify it works.

**Comment by breons** [comment]
Also, did that rerun generate the transcripts.gtf file?

**Comment by MrsLaviniaG** [comment]
Ok and running the pipeline again, without deleting anything, just running it on the login node gives me ... success!

===================================== Stage plot_fusion (test) =====================================
[1] "Plotting: BCR:ABL1"
[1] "------------------------------------------------------"
[1] "Libraries and ancillary files loaded. Creating Tracks."
[1] "Tracks created, printing PDF."
[1] "PDF created."

======================================== Pipeline Succeeded ========================================
15:49:32 MSG:  Finished at Wed Jul 11 15:49:32 AEST 2018
15:49:32 MSG:  Outputs are:
                /g/data3/gx8/extras/gordonl/Clinker/clinker_results/alignment/test/Aligned.sortedByCoord.out.bam
                /g/data/gx8/extras/gordonl/Clinker/clinker_results/genome/Genome

And yes, the missing spaces above are due to copy/paste.

**Comment by breons** [comment]
Hooray! First issue post publication received and solved, how is that PDF looking?

Thanks for trying Clinker, I hope you have some use for it.
