### ISSUE TITLE
Start out with full fastq?

### ISSUE THREAD

**Issue by messersc** [Oshlack/Clinker#7]
Hi,

I have some fusion predictions from fusioncatcher and pizzly and I might add JAFFA soon. On my quest to visualize these data, I have found chimeraviz and Clinker, which both seem to do a good job.

Looking through the documentation, both programs create a new "reference" to align reads to. Chimeraviz suggests to use the "fished" FASTQ some tools give you (pizzly and fusioncatcher do), while it looks like with Clinker, you use the full FASTQs. The first option is clearly faster, although from reading your paper for the P2RY8-CRLF2 you got more reads by starting from the full FASTQ.

Guess I really need to try both to find out for my case, but are there any other pitfalls I should be aware of when using Clinker?

Thanks for you help,
Clemens

**Comment by breons** [comment]
Hi there, 

Thanks for giving it a try. Hopefully, you get some utility out of it for your fusion visualisations.

If you do run into any pitfalls or feel that there are modifications that would improve the tool for you, feel free to drop me a line and I'll try and resolve them for you. 

Good luck!
